apiVersion: batch/v1
kind: Job
metadata:
  name: hello-py-job
spec:
  template:
    metadata:
      name: hello-py-job
    spec:
      containers:
      - name: python-app
        image: dockerfoam/hello-py:latest
      restartPolicy: Never
