---
sudo: required
dist: focal


notifications:
  slack:
    on_failure: always


matrix:
  fast_finish: true
  include:

# Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=SystemVerification Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=SystemVerification 
    # - name: "weavescope minikube wo snaps on focal amd64"
    #   dist: focal
    #   arch: amd64
    #   language: python
    #   # python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     - sudo make deploy-minikube-latest
    #     - sudo make deploy-weavescope
    #   after_success:
    #     - deactivate

# app/deploy-minikube_latest.sh: line 17: /usr/local/bin/minikube: cannot execute binary file: Exec format error
    # - name: "weavescope minikube wo snaps on focal arm64"
    #   dist: focal
    #   arch: arm64
    #   language: python
    #   # python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     - sudo make deploy-minikube-latest
    #     - sudo make deploy-weavescope
    #   after_success:
    #     - deactivate

# app/deploy-minikube_latest.sh: line 17: /usr/local/bin/minikube: cannot execute binary file: Exec format error
    # - name: "weavescope minikube wo snaps Python 3.7 on bionic arm64"
    #   dist: bionic
    #   arch: arm64
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     - sudo make deploy-minikube-latest
    #     - sudo make deploy-weavescope
    #   after_success:
    #     - deactivate

    - name: "weavescope minikube w snaps Python 3.7 on bionic amd64"
      dist: bionic
      arch: amd64
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-minikube-latest
        - sudo make deploy-weavescope
      after_success:
        - deactivate