---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation

notifications:
  slack:
    on_failure: always

fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:


#   # =============================================macOS=============================================

    - name: "docker docker-machine vbox  Python 2.7.17 on macOS 10.15.4 osx xcode11.5" #installer: Error - Your CPU does not have the features necessary for Multipass. Installation cannot proceed.
      os: osx
      osx_image: xcode11.5
      language: shell
      addons:
        homebrew:
          packages:
          - docker
          - docker-machine
          update: true
      # addons:
      #   homebrew:
      #     # brewfile: Brewfile.travis
      #     # packages:
      #     #   - multipass
      #     # taps: homebrew/cask-versions
          casks: # Installing Casks
            - virtualbox
      #     update: true
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      script:
        # - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" #Install Homebrew
        # - brew cask install multipass
        # - multipass version
        # - sudo brew install docker docker-machine
        - docker version
        # - brew cask install virtualbox
        - brew list --versions
        - sudo docker-machine create --driver virtualbox default
        - sudo docker-machine ls
        - sudo docker-machine env default
        - eval "$(docker-machine env default)"
        - sudo docker run hello-world
        - sudo docker-machine stop default
        # - sudo multipass set local.driver=virtualbox #If you’d like to use VirtualBox, run the following in the terminal after installing Multipass
      after_success:
        - brew cask uninstall multipass
        - deactivate

#   # =============================================windows=============================================

# https://docs.docker.com/docker-for-windows/install/
# Windows 10 64-bit: Pro, Enterprise, or Education (Build 15063 or later).
# Hyper-V and Containers Windows features must be enabled.
    - name: "docker desktop choco k8s  Python 3.8 on Windows"
      os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      script:
          - choco install -y docker-desktop #https://docs.docker.com/docker-for-windows/kubernetes/
          # - pwsh  docker --version
          # - pwsh docker run hello-world
          # - pwsh docker image ls
      after_success:
        - deactivate
