---
sudo: required
dist: focal


notifications:
  slack:
    on_failure: always


matrix:
  fast_finish: true
  include:

    - name: "kubeflow minikube wo snaps  on focal amd64"
      dist: focal
      arch: amd64
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-kubeflow #installing minikube included
      after_success:
        - deactivate

    - name: "kubeflow minikube wo snaps  on focal arm64"
      dist: focal
      arch: arm64
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-kubeflow #installing minikube included
      after_success:
        - deactivate


    - name: "kubeflow minikube wo snaps on bionic arm64"
      dist: bionic
      arch: arm64
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-kubeflow #installing minikube included
      after_success:
        - deactivate

    - name: "kubeflow minikube wo snaps Python 3.7 on bionic amd64"
      dist: bionic
      arch: amd64
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-kubeflow #installing minikube included
      after_success:
        - deactivate
