---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:

# The connection to the server localhost:8080 was refused - did you specify the right host or port?
    # - name: "voting-app minikube w snaps on bionic amd64"
    #   dist: bionic
    #   arch: amd64
    #   addons:
    #       snaps:
    #         - name: minikube
    #           confinement: classic
    #           channel: latest/stable
    #         - name: kubectl
    #           confinement: classic
    #           channel: latest/stable
    #         - name: helm
    #           confinement: classic
    #           channel: latest/stable    
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     # - sudo make deploy-minikuböe-latest
    #     - sudo make deploy-voting-app
    #   after_success:
    #     - deactivate

# app/deploy-minikube_latest.sh: line 25: /usr/local/bin/minikube: cannot execute binary file: Exec format error
    # - name: "voting-app minikube wo snaps on bionic arm64"
    #   dist: bionic
    #   arch: arm64
    #   language: python
    #   # python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     - sudo make deploy-minikube-latest
    #     - sudo make deploy-voting-app
    #   after_success:
    #     - deactivate

# X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=SystemVerification 
    # - name: "voting-app minikube wo snaps on focal amd64"
    #   dist: focal
    #   arch: amd64
    #   language: python
    #   # python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     - sudo make deploy-minikube-latest
    #     - sudo make deploy-voting-app
    #   after_success:
    #     - deactivate
    
    # TESTED OK
    - name: "voting app minikube wo snaps Python 3.7 on bionic amd64"
      dist: bionic
      arch: amd64
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-minikube-latest
        - sudo make deploy-voting-app
      after_success:
        - deactivate
