apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        pod.boostport.com/vault-approle: jenkins
        pod.boostport.com/vault-init-container: get-vault-token
    spec:
      containers:
      - name: sample-app
        image: boostport/kubernetes-vault-sample-app
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      initContainers:
      - name: get-vault-token
        image: boostport/kubernetes-vault-init
        imagePullPolicy: Always
        env:
        - name: VAULT_ROLE_ID
          value: e785419d-ddf3-71e9-c9a7-17f119303d29
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      volumes:
      - name: vault-token
        emptyDir: {}